CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Consumers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" character varying(100) NOT NULL,
    "ResetToken" text,
    "ResetTokenExpiry" timestamp with time zone,
    CONSTRAINT "PK_Consumers" PRIMARY KEY ("Id")
);

CREATE TABLE "Chats" (
    "Id" text NOT NULL,
    "Type" integer NOT NULL,
    "Name" text,
    "AdminId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Chats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Chats_Consumers_AdminId" FOREIGN KEY ("AdminId") REFERENCES "Consumers" ("Id")
);

CREATE TABLE "ChatParticipants" (
    "ChatId" text NOT NULL,
    "UserId" text NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatParticipants" PRIMARY KEY ("ChatId", "UserId"),
    CONSTRAINT "FK_ChatParticipants_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatParticipants_Consumers_UserId" FOREIGN KEY ("UserId") REFERENCES "Consumers" ("Id")
);

CREATE TABLE "Messages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" text NOT NULL,
    "SenderFullName" text NOT NULL,
    "SenderEmail" text NOT NULL,
    "Content" text NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ChatId" text,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES "Chats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Consumers_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Consumers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatParticipants_UserId" ON "ChatParticipants" ("UserId");

CREATE INDEX "IX_Chats_AdminId" ON "Chats" ("AdminId");

CREATE INDEX "IX_Messages_ChatId" ON "Messages" ("ChatId");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260311095335_InitialPostgres', '8.0.0');

COMMIT;

